<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Connexion_password_login</name>
   <tag></tag>
   <elementGuidId>f2c93ead-511c-4d1a-a78e-067fd87641e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e85a697f-53f8-4f22-b6bd-3ae4dc3167b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_login</value>
      <webElementGuid>eb98eb3b-17c2-4d94-bd32-6de2ef6bfa70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_input_password__3QtcC</value>
      <webElementGuid>bd660d6d-f906-4494-8fd4-179aaa4c50e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mot de passe</value>
      <webElementGuid>41bc997d-35f5-4c31-b88f-cc23837ba808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>42c66847-d569-4227-b789-2fbd8c97c4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_login&quot;)</value>
      <webElementGuid>e694fa6f-23b9-4636-9f90-778d1fd097f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_login']</value>
      <webElementGuid>32721e35-d6fa-4259-a295-ae6174c27f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='style_container_input_password___0rEz']/input</value>
      <webElementGuid>54907d2b-119a-49a1-a6ef-de843dcd01e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6ba11703-7925-4b4c-ba66-baf2b80ae43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'password_login' and @placeholder = 'Mot de passe' and @type = 'password']</value>
      <webElementGuid>ad2643ee-3701-497c-842a-1a3799a0d4c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
