<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ajouter au panier</name>
   <tag></tag>
   <elementGuidId>b5ed9228-4f65-4bf2-879e-ec9a4a556ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#style_btn_add_cart__gTXM7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='style_btn_add_cart__gTXM7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>162f5094-0c53-4ad8-8f93-e0e2795bd174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>style_btn_add_cart__gTXM7</value>
      <webElementGuid>61eea3c6-c46a-4696-ae5f-b9add1cf1d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajouter au panier</value>
      <webElementGuid>2de6fecb-fe8e-4c9f-9fb3-3130cd8bf62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;style_btn_add_cart__gTXM7&quot;)</value>
      <webElementGuid>19dc2764-40ca-4a7f-bd59-b2436f099ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='style_btn_add_cart__gTXM7']</value>
      <webElementGuid>87297a63-96e3-441c-bf77-ed36049e5220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='style_detail_wrapper__a7fpS']/button</value>
      <webElementGuid>c30ef7fd-e699-4076-90fc-b1ff691860dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('J', &quot;'&quot;, 'ai un code promo')])[1]/following::button[1]</value>
      <webElementGuid>e62c89c2-aa6e-4b95-8f5e-6ac7df002182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::button[2]</value>
      <webElementGuid>6eb56c0d-080b-4a1f-a0ac-64d16bf14e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider votre commande'])[1]/preceding::button[2]</value>
      <webElementGuid>628e44d5-e95e-4e2d-8890-ad3dc1325ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choisir une methode de livraison'])[1]/preceding::button[2]</value>
      <webElementGuid>1faac6b2-4890-403a-9444-62ea65be8df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajouter au panier']/parent::*</value>
      <webElementGuid>f96ba815-5b3c-4b52-82dc-8d338030d140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/button</value>
      <webElementGuid>a447a345-c68f-4f06-93cc-2625bd6c49d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'style_btn_add_cart__gTXM7' and (text() = 'Ajouter au panier' or . = 'Ajouter au panier')]</value>
      <webElementGuid>7c76e0d7-7efe-4f70-8183-a937e0cba63f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
