<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Commander_style_btn_close__9uLzQ</name>
   <tag></tag>
   <elementGuidId>1c30caeb-aa58-45e6-9931-90db62a5de6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#style_btn_close__9uLzQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='style_btn_close__9uLzQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>befed1ed-33ea-4612-92a3-83092689cd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>style_btn_close__9uLzQ</value>
      <webElementGuid>6750d6ab-4fff-462d-8c05-fcdf57dcc22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;style_btn_close__9uLzQ&quot;)</value>
      <webElementGuid>65aa7763-b465-415e-ba79-153a63c23ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='style_btn_close__9uLzQ']</value>
      <webElementGuid>8591a6d6-e772-4c97-b070-aeeba48ddcd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='style_content_detail__ZNkX9']/button</value>
      <webElementGuid>ca76a023-04bf-4bb2-9332-cf746ca4373a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commander'])[1]/following::button[1]</value>
      <webElementGuid>fe5a7ff5-73f0-494c-b560-f1d9ab0556dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vider le panier'])[1]/following::button[2]</value>
      <webElementGuid>39873a1d-f471-41bc-bdba-b59512a31e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-shirt en coton biologique'])[1]/preceding::button[7]</value>
      <webElementGuid>11fa4770-476c-4b96-b7e0-f8b81b3e239b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::button[9]</value>
      <webElementGuid>7fd486fd-05a7-435f-8589-1d3f4b65298c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/button</value>
      <webElementGuid>a48c670d-a894-47f5-8a64-49c114c3c8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'style_btn_close__9uLzQ']</value>
      <webElementGuid>b29636a5-8b14-4fc6-be52-31e7ad09c68e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
