<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2</name>
   <tag></tag>
   <elementGuidId>be7def03-a11a-46a4-aca1-28bf81998818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#style_content_cart_wrapper__mqNbf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='style_content_cart_wrapper__mqNbf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b202f50f-5551-4819-8712-070731381b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>style_content_cart_wrapper__mqNbf</value>
      <webElementGuid>d95bb642-62e3-4a35-841e-24beeaf10585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2</value>
      <webElementGuid>02fa25c2-95ed-417a-978d-25af056409f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;style_content_cart_wrapper__mqNbf&quot;)</value>
      <webElementGuid>df7c0a93-e7c2-4e3e-9d42-a74181a773b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='style_content_cart_wrapper__mqNbf']</value>
      <webElementGuid>902e577f-9f7f-493b-b79a-2c5dc652e7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='style_header_navBar__hdNqL']/div[3]</value>
      <webElementGuid>9cf732cb-ece1-49fa-b61c-0aa7ad5e7dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Z-Train'])[1]/following::div[3]</value>
      <webElementGuid>589e257a-6e3c-4023-8180-b948c76925f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::div[4]</value>
      <webElementGuid>29f4b21d-3af3-4a34-9b9a-9e38d92d1aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inconnu'])[1]/preceding::div[1]</value>
      <webElementGuid>f4c6abe5-248b-4303-a7b4-932bbaf58685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fredytcheuguen@gmail.com'])[1]/preceding::div[2]</value>
      <webElementGuid>b9278105-e3b3-4494-887d-eb1124904f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[3]</value>
      <webElementGuid>ffe72ae7-d69d-4178-9663-0be1733d70df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'style_content_cart_wrapper__mqNbf' and (text() = ' 2' or . = ' 2')]</value>
      <webElementGuid>4b8b69ec-a3c3-4983-bb7c-eaba874b204e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
