<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Connexion_password_login</name>
   <tag></tag>
   <elementGuidId>65ec7b42-fb75-46d0-9929-4eb36355236e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78af1e7c-8a88-41c8-91f9-71c5556dd1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_login</value>
      <webElementGuid>6c0db985-08fa-4a5c-a725-4192ace3732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_input_password__3QtcC</value>
      <webElementGuid>93607df4-1816-47ab-a1bf-d8105ebbe596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mot de passe</value>
      <webElementGuid>2429ab16-952e-4f30-b340-66cd6351c936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e74cf066-ab7e-4f83-8e46-72b3c3c69f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B</value>
      <webElementGuid>5ed86846-2d76-40c2-be49-43ffc92961f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_login&quot;)</value>
      <webElementGuid>77714845-a4fc-4e27-9a0d-1d893c994a04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_login']</value>
      <webElementGuid>f9d8e901-99f1-4f4c-89f6-e83e539dbd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='style_container_input_password___0rEz']/input</value>
      <webElementGuid>68bc67ec-8026-4458-a950-b91c1344651c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>dc8cba33-0694-4e4b-9047-da699e743a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'password_login' and @placeholder = 'Mot de passe' and @type = 'password']</value>
      <webElementGuid>72400b48-37e3-4ec4-8c82-3275c317e008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
