<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Z-Train_style_input_navbar_search__Scaxy</name>
   <tag></tag>
   <elementGuidId>f907743f-3cee-42a4-b2a4-1c008910f6c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#style_input_navbar_search__Scaxy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='style_input_navbar_search__Scaxy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd93c756-60b1-4ce6-a27b-ccf1aadcac06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e863314-4030-45cc-8c6c-1cfe13162804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>style_input_navbar_search__Scaxy</value>
      <webElementGuid>94191160-c42c-45e8-9367-412e6421cd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechecher un produit</value>
      <webElementGuid>b3b25f2c-1992-4d10-9673-950c384fab83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;style_input_navbar_search__Scaxy&quot;)</value>
      <webElementGuid>5ad9b094-fb95-41ba-933c-27bb1c4ac249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='style_input_navbar_search__Scaxy']</value>
      <webElementGuid>4c3881b9-b5d4-44fe-8a6f-44ab13bdf560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='style_content_input_wrapper__eNPFq']/input</value>
      <webElementGuid>5acd6271-49c6-4854-ab8f-79e7be5df803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>35bc29ea-122a-47ac-9800-87d3b8f09f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'style_input_navbar_search__Scaxy' and @placeholder = 'Rechecher un produit']</value>
      <webElementGuid>34402d48-b27e-4d52-816e-b78282782217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
