<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Connexion_email_login</name>
   <tag></tag>
   <elementGuidId>8a770917-9f76-4b66-8442-003ada5d8729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>376c2bfd-f7c3-48fd-8dcf-469d7d885547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_login</value>
      <webElementGuid>2c803715-46e7-494a-ac86-ed6d47e0a862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_input__TGKMb</value>
      <webElementGuid>160874c5-756c-4378-9ade-4e86ad56dafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>a4e0de39-422c-4f98-901f-1e972dd48a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_login&quot;)</value>
      <webElementGuid>e9d72ffb-f23f-45bb-86c8-9dc07eb5c291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_login']</value>
      <webElementGuid>712c847a-93c3-47a6-93b1-0abe7e594972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='style_content_form__yXJox']/input</value>
      <webElementGuid>b50b4e5d-377f-4573-aa53-7a8bf88ead3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f03e99c2-5328-4611-8e3c-b01e5fe83c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email_login' and @placeholder = 'Email']</value>
      <webElementGuid>c6e9b5b5-363f-4be2-8901-32046ab4a67a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
