<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>fa7b0b83-cae0-41cc-94b6-d84b493111df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#style_content_cart_wrapper__mqNbf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='style_content_cart_wrapper__mqNbf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11fa67bf-7c55-460e-bda5-5514f76e06ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>style_content_cart_wrapper__mqNbf</value>
      <webElementGuid>8226af31-13ad-4b53-9eb1-78f9a48a3ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1</value>
      <webElementGuid>3dfcb408-6a94-4a77-b53e-98e6ba4f779d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;style_content_cart_wrapper__mqNbf&quot;)</value>
      <webElementGuid>66166cad-4143-4950-b0b6-a3a7dca299de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='style_content_cart_wrapper__mqNbf']</value>
      <webElementGuid>80496e8e-1f23-4dff-bdd9-fb0978a5e955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='style_header_navBar__hdNqL']/div[3]</value>
      <webElementGuid>9758574b-4543-4dd2-ba17-bc6c76847536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Z-Train'])[1]/following::div[3]</value>
      <webElementGuid>df364e97-26e9-4c56-92b4-fc3958958415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valider'])[1]/following::div[4]</value>
      <webElementGuid>40c333f4-c5bd-4ef5-886f-b71fe3617543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inconnu'])[1]/preceding::div[1]</value>
      <webElementGuid>8ff61286-83dc-46ac-8d25-cdaea9607bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fredytcheuguen@gmail.com'])[1]/preceding::div[2]</value>
      <webElementGuid>c8fc9012-a270-41f3-82d0-f6b297bc8bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[3]</value>
      <webElementGuid>65f68dc3-4b89-4e4c-b2ce-f415000373d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'style_content_cart_wrapper__mqNbf' and (text() = ' 1' or . = ' 1')]</value>
      <webElementGuid>31575bcb-578d-4ba9-8081-e92e4baa4e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
