<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3</name>
   <tag></tag>
   <elementGuidId>797ee156-32bb-4abb-89da-2f875c9a9215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.style_quantity__qJbQ3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='style_card_wrapper__hrc1I']/div/div[3]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>548abe1e-cde9-47d4-961c-159761b6916b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_quantity__qJbQ3</value>
      <webElementGuid>df549b14-fd32-4f75-a655-387939f58be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9f48e219-28e1-49dd-a1fc-3ce3bc4bcb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;style_card_wrapper__hrc1I&quot;)/div[@class=&quot;style_card__JLMp6&quot;]/div[@class=&quot;style_quantity_wrapper__EFj5M&quot;]/span[@class=&quot;style_quantity__qJbQ3&quot;]</value>
      <webElementGuid>266d58d7-e27b-49b5-b4c8-b4a137b052c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='style_card_wrapper__hrc1I']/div/div[3]/span[2]</value>
      <webElementGuid>40b59c94-8033-4687-a953-08697adb8d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon panier'])[1]/following::span[4]</value>
      <webElementGuid>2a9b3a83-a167-44c7-9b20-7e73a95cf1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::span[2]</value>
      <webElementGuid>c46b0896-9bf4-4905-8fd7-4e84f75cfe3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vider le panier'])[1]/preceding::span[2]</value>
      <webElementGuid>8d804b21-41e8-4fc7-b201-08fa6b5cf9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>d720deec-bb86-45c5-a231-30156ceec371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>14fe9450-acfe-4a40-83f6-e1ea81c68690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '3' or . = '3')]</value>
      <webElementGuid>4aea6b1c-addc-47e1-8b74-6d1d06906b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
